// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file auth/v2/auth.proto (package auth.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AssociateHubRequest, AssociateHubResponse, ClaimHubTokenRequest, ClaimHubTokenResponse, ListHubsRequest, ListHubsResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, RevokeHubRequest, RevokeHubResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ====== Service ======
 *
 * @generated from service auth.v2.AuthService
 */
export const AuthService = {
  typeName: "auth.v2.AuthService",
  methods: {
    /**
     * Public — no token required
     *
     * @generated from rpc auth.v2.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v2.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Protected — valid user token required
     *
     * @generated from rpc auth.v2.AuthService.AssociateHub
     */
    associateHub: {
      name: "AssociateHub",
      I: AssociateHubRequest,
      O: AssociateHubResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Public — hub has no JWT yet on first boot
     *
     * @generated from rpc auth.v2.AuthService.ClaimHubToken
     */
    claimHubToken: {
      name: "ClaimHubToken",
      I: ClaimHubTokenRequest,
      O: ClaimHubTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v2.AuthService.ListHubs
     */
    listHubs: {
      name: "ListHubs",
      I: ListHubsRequest,
      O: ListHubsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v2.AuthService.RevokeHub
     */
    revokeHub: {
      name: "RevokeHub",
      I: RevokeHubRequest,
      O: RevokeHubResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

