// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file garden/v2/garden.proto (package garden.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetLastRequest, GetLastResponse, GetSummaryRequest, GetSummaryResponse, InsertSensorDataRequest, InsertSensorDataResponse, ListProbesForHubNameRequest, ListProbesForHubNameResponse } from "./garden_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ====== Service ======
 *
 * @generated from service garden.v2.GardenService
 */
export const GardenService = {
  typeName: "garden.v2.GardenService",
  methods: {
    /**
     * Insert a new sensor measurement. Hub-only.
     *
     * @generated from rpc garden.v2.GardenService.InsertSensorData
     */
    insertSensorData: {
      name: "InsertSensorData",
      I: InsertSensorDataRequest,
      O: InsertSensorDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Read aggregated sensor data scoped to the caller's hubs.
     *
     * @generated from rpc garden.v2.GardenService.GetSummary
     */
    getSummary: {
      name: "GetSummary",
      I: GetSummaryRequest,
      O: GetSummaryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List all probes registered under a hub owned by the authenticated user. User-only.
     *
     * @generated from rpc garden.v2.GardenService.ListProbesForHubName
     */
    listProbesForHubName: {
      name: "ListProbesForHubName",
      I: ListProbesForHubNameRequest,
      O: ListProbesForHubNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Return the most recent sensor reading for a probe owned by the caller. User-only.
     *
     * @generated from rpc garden.v2.GardenService.GetLast
     */
    getLast: {
      name: "GetLast",
      I: GetLastRequest,
      O: GetLastResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

