// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file chat/v1/chat.proto (package chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SendMessageRequest, SendMessageResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.v1.ChatService
 */
export const ChatService = {
  typeName: "chat.v1.ChatService",
  methods: {
    /**
     * @generated from rpc chat.v1.ChatService.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: SendMessageRequest,
      O: SendMessageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

