// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file chat/v1/chat.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/chat.proto.
 */
export const file_chat_v1_chat: GenFile = /*@__PURE__*/
  fileDesc("ChJjaGF0L3YxL2NoYXQucHJvdG8SB2NoYXQudjEiUAoSU2VuZE1lc3NhZ2VSZXF1ZXN0Eg8KB21lc3NhZ2UYASABKAkSKQoGcGxhbnRzGAIgAygLMhkuY2hhdC52MS5DaGF0UGxhbnRDb250ZXh0IiQKE1NlbmRNZXNzYWdlUmVzcG9uc2USDQoFcmVwbHkYASABKAkiVQoQQ2hhdFBsYW50Q29udGV4dBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhAKCHF1YW50aXR5GAMgASgFEhUKDXByb2JlX25vZGVfaWQYBCABKAky9QIKC0NoYXRTZXJ2aWNlEsQCCgtTZW5kTWVzc2FnZRIbLmNoYXQudjEuU2VuZE1lc3NhZ2VSZXF1ZXN0GhwuY2hhdC52MS5TZW5kTWVzc2FnZVJlc3BvbnNlIvkBkkHKAQoHQ2hhdCB2MRIcU2VuZE1lc3NhZ2UgKENoYXRTZXJ2aWNlIHYxKRqSAVNlbmQgYSB1c2VyIG1lc3NhZ2UgdG8gdGhlIEhhcnZlc3QgSHViIEFJIGFzc2lzdGFudC4gVGhlIGJhY2tlbmQgaW5qZWN0cyBvd25lZCBnYXJkZW4gcHJvYmUgY29udGV4dCBiZWZvcmUgcHJveHlpbmcgdG8gdGhlIGNvbmZpZ3VyZWQgQUkgcHJvdmlkZXIuYgwKCgoGYmVhcmVyEgCC0+STAiU6ASoiIC9jaGF0LnYxLkNoYXRTZXJ2aWNlL1NlbmRNZXNzYWdlGh+SQRwSGkFJIGFzc2lzdGFudCBjaGF0IHNlcnZpY2UuQuIEWj1naXRodWIuY29tL2hhcnZlc3RodWItZ2FyZGVuaW5nLXRvb2wvcHJvdG9zLWdvL2NoYXQvdjE7Y2hhdHYxkkGfBBL1AgoLQ2hhdCBBUEkgdjESyQJBSSBhc3Npc3RhbnQgY2hhdCBBUEkgZm9yIEhhcnZlc3QgSHViIG1vYmlsZSBjbGllbnRzLiBUaGUgYmFja2VuZCBwcm94aWVzIHVzZXIgbWVzc2FnZXMgdG8gdGhlIGNvbmZpZ3VyZWQgQUkgcHJvdmlkZXIgYW5kIGVucmljaGVzIHJlcXVlc3RzIHdpdGggZ2FyZGVuIGNvbnRleHQgb3duZWQgYnkgdGhlIGF1dGhlbnRpY2F0ZWQgdXNlci4KCioqQXV0aGVudGljYXRpb246KiogQWxsIGVuZHBvaW50cyByZXF1aXJlIGEgdXNlciBCZWFyZXIgdG9rZW4uIFByb3ZpZGVyIEFQSSBrZXlzIGFyZSBzZXJ2ZXItc2lkZSBvbmx5IGFuZCBhcmUgbmV2ZXIgZXhwb3NlZCB0byBjbGllbnRzLiIVChNIYXJ2ZXN0IEh1YiBQcm9qZWN0MgMxLjAqAgECMhBhcHBsaWNhdGlvbi9qc29uMhFhcHBsaWNhdGlvbi9wcm90bzoQYXBwbGljYXRpb24vanNvbjoRYXBwbGljYXRpb24vcHJvdG9aSQpHCgZiZWFyZXISPQgCEihVc2VyIEpXVCB0b2tlbi4gRm9ybWF0OiAnQmVhcmVyIDx0b2tlbj4nGg1BdXRob3JpemF0aW9uIAJiDAoKCgZiZWFyZXISAGIGcHJvdG8z", [file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations]);

/**
 * @generated from message chat.v1.SendMessageRequest
 */
export type SendMessageRequest = Message<"chat.v1.SendMessageRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: repeated chat.v1.ChatPlantContext plants = 2;
   */
  plants: ChatPlantContext[];
};

/**
 * Describes the message chat.v1.SendMessageRequest.
 * Use `create(SendMessageRequestSchema)` to create a new message.
 */
export const SendMessageRequestSchema: GenMessage<SendMessageRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_chat, 0);

/**
 * @generated from message chat.v1.SendMessageResponse
 */
export type SendMessageResponse = Message<"chat.v1.SendMessageResponse"> & {
  /**
   * @generated from field: string reply = 1;
   */
  reply: string;
};

/**
 * Describes the message chat.v1.SendMessageResponse.
 * Use `create(SendMessageResponseSchema)` to create a new message.
 */
export const SendMessageResponseSchema: GenMessage<SendMessageResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_chat, 1);

/**
 * @generated from message chat.v1.ChatPlantContext
 */
export type ChatPlantContext = Message<"chat.v1.ChatPlantContext"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 quantity = 3;
   */
  quantity: number;

  /**
   * @generated from field: string probe_node_id = 4;
   */
  probeNodeId: string;
};

/**
 * Describes the message chat.v1.ChatPlantContext.
 * Use `create(ChatPlantContextSchema)` to create a new message.
 */
export const ChatPlantContextSchema: GenMessage<ChatPlantContext> = /*@__PURE__*/
  messageDesc(file_chat_v1_chat, 2);

/**
 * @generated from service chat.v1.ChatService
 */
export const ChatService: GenService<{
  /**
   * @generated from rpc chat.v1.ChatService.SendMessage
   */
  sendMessage: {
    methodKind: "unary";
    input: typeof SendMessageRequestSchema;
    output: typeof SendMessageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chat_v1_chat, 0);

