// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateHubTokenRequest, CreateHubTokenResponse, ListHubTokensRequest, ListHubTokensResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, RevokeHubTokenRequest, RevokeHubTokenResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ====== Service ======
 *
 * @generated from service auth.v1.AuthService
 */
export const AuthService = {
  typeName: "auth.v1.AuthService",
  methods: {
    /**
     * Public — no token required
     *
     * @generated from rpc auth.v1.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Protected — valid user token required
     *
     * @generated from rpc auth.v1.AuthService.CreateHubToken
     */
    createHubToken: {
      name: "CreateHubToken",
      I: CreateHubTokenRequest,
      O: CreateHubTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.ListHubTokens
     */
    listHubTokens: {
      name: "ListHubTokens",
      I: ListHubTokensRequest,
      O: ListHubTokensResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.RevokeHubToken
     */
    revokeHubToken: {
      name: "RevokeHubToken",
      I: RevokeHubTokenRequest,
      O: RevokeHubTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

