// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiMgoPUmVnaXN0ZXJSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIjIKEFJlZ2lzdGVyUmVzcG9uc2USDwoHdXNlcl9pZBgBIAEoCRINCgV0b2tlbhgCIAEoCSIvCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiHgoNTG9naW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCSIpChVDcmVhdGVIdWJUb2tlblJlcXVlc3QSEAoIaHViX25hbWUYASABKAkiJwoWQ3JlYXRlSHViVG9rZW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCSIWChRMaXN0SHViVG9rZW5zUmVxdWVzdCJRCgxIdWJUb2tlbkluZm8SCgoCaWQYASABKAkSEAoIaHViX25hbWUYAiABKAkSEgoKY3JlYXRlZF9hdBgDIAEoAxIPCgdyZXZva2VkGAQgASgIIj4KFUxpc3RIdWJUb2tlbnNSZXNwb25zZRIlCgZ0b2tlbnMYASADKAsyFS5hdXRoLnYxLkh1YlRva2VuSW5mbyIpChVSZXZva2VIdWJUb2tlblJlcXVlc3QSEAoIdG9rZW5faWQYASABKAkiGAoWUmV2b2tlSHViVG9rZW5SZXNwb25zZTL8AgoLQXV0aFNlcnZpY2USPwoIUmVnaXN0ZXISGC5hdXRoLnYxLlJlZ2lzdGVyUmVxdWVzdBoZLmF1dGgudjEuUmVnaXN0ZXJSZXNwb25zZRI2CgVMb2dpbhIVLmF1dGgudjEuTG9naW5SZXF1ZXN0GhYuYXV0aC52MS5Mb2dpblJlc3BvbnNlElEKDkNyZWF0ZUh1YlRva2VuEh4uYXV0aC52MS5DcmVhdGVIdWJUb2tlblJlcXVlc3QaHy5hdXRoLnYxLkNyZWF0ZUh1YlRva2VuUmVzcG9uc2USTgoNTGlzdEh1YlRva2VucxIdLmF1dGgudjEuTGlzdEh1YlRva2Vuc1JlcXVlc3QaHi5hdXRoLnYxLkxpc3RIdWJUb2tlbnNSZXNwb25zZRJRCg5SZXZva2VIdWJUb2tlbhIeLmF1dGgudjEuUmV2b2tlSHViVG9rZW5SZXF1ZXN0Gh8uYXV0aC52MS5SZXZva2VIdWJUb2tlblJlc3BvbnNlQj9aPWdpdGh1Yi5jb20vaGFydmVzdGh1Yi1nYXJkZW5pbmctdG9vbC9wcm90b3MtZ28vYXV0aC92MTthdXRodjFiBnByb3RvMw");

/**
 * @generated from message auth.v1.RegisterRequest
 */
export type RegisterRequest = Message<"auth.v1.RegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.RegisterResponse
 */
export type RegisterResponse = Message<"auth.v1.RegisterResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message auth.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * @generated from message auth.v1.LoginRequest
 */
export type LoginRequest = Message<"auth.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * @generated from message auth.v1.LoginResponse
 */
export type LoginResponse = Message<"auth.v1.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from message auth.v1.CreateHubTokenRequest
 */
export type CreateHubTokenRequest = Message<"auth.v1.CreateHubTokenRequest"> & {
  /**
   * @generated from field: string hub_name = 1;
   */
  hubName: string;
};

/**
 * Describes the message auth.v1.CreateHubTokenRequest.
 * Use `create(CreateHubTokenRequestSchema)` to create a new message.
 */
export const CreateHubTokenRequestSchema: GenMessage<CreateHubTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * @generated from message auth.v1.CreateHubTokenResponse
 */
export type CreateHubTokenResponse = Message<"auth.v1.CreateHubTokenResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message auth.v1.CreateHubTokenResponse.
 * Use `create(CreateHubTokenResponseSchema)` to create a new message.
 */
export const CreateHubTokenResponseSchema: GenMessage<CreateHubTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * @generated from message auth.v1.ListHubTokensRequest
 */
export type ListHubTokensRequest = Message<"auth.v1.ListHubTokensRequest"> & {
};

/**
 * Describes the message auth.v1.ListHubTokensRequest.
 * Use `create(ListHubTokensRequestSchema)` to create a new message.
 */
export const ListHubTokensRequestSchema: GenMessage<ListHubTokensRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * @generated from message auth.v1.HubTokenInfo
 */
export type HubTokenInfo = Message<"auth.v1.HubTokenInfo"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string hub_name = 2;
   */
  hubName: string;

  /**
   * Unix milliseconds
   *
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;

  /**
   * @generated from field: bool revoked = 4;
   */
  revoked: boolean;
};

/**
 * Describes the message auth.v1.HubTokenInfo.
 * Use `create(HubTokenInfoSchema)` to create a new message.
 */
export const HubTokenInfoSchema: GenMessage<HubTokenInfo> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 7);

/**
 * @generated from message auth.v1.ListHubTokensResponse
 */
export type ListHubTokensResponse = Message<"auth.v1.ListHubTokensResponse"> & {
  /**
   * @generated from field: repeated auth.v1.HubTokenInfo tokens = 1;
   */
  tokens: HubTokenInfo[];
};

/**
 * Describes the message auth.v1.ListHubTokensResponse.
 * Use `create(ListHubTokensResponseSchema)` to create a new message.
 */
export const ListHubTokensResponseSchema: GenMessage<ListHubTokensResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 8);

/**
 * @generated from message auth.v1.RevokeHubTokenRequest
 */
export type RevokeHubTokenRequest = Message<"auth.v1.RevokeHubTokenRequest"> & {
  /**
   * @generated from field: string token_id = 1;
   */
  tokenId: string;
};

/**
 * Describes the message auth.v1.RevokeHubTokenRequest.
 * Use `create(RevokeHubTokenRequestSchema)` to create a new message.
 */
export const RevokeHubTokenRequestSchema: GenMessage<RevokeHubTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 9);

/**
 * @generated from message auth.v1.RevokeHubTokenResponse
 */
export type RevokeHubTokenResponse = Message<"auth.v1.RevokeHubTokenResponse"> & {
};

/**
 * Describes the message auth.v1.RevokeHubTokenResponse.
 * Use `create(RevokeHubTokenResponseSchema)` to create a new message.
 */
export const RevokeHubTokenResponseSchema: GenMessage<RevokeHubTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 10);

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Public — no token required
   *
   * @generated from rpc auth.v1.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Protected — valid user token required
   *
   * @generated from rpc auth.v1.AuthService.CreateHubToken
   */
  createHubToken: {
    methodKind: "unary";
    input: typeof CreateHubTokenRequestSchema;
    output: typeof CreateHubTokenResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.ListHubTokens
   */
  listHubTokens: {
    methodKind: "unary";
    input: typeof ListHubTokensRequestSchema;
    output: typeof ListHubTokensResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.RevokeHubToken
   */
  revokeHubToken: {
    methodKind: "unary";
    input: typeof RevokeHubTokenRequestSchema;
    output: typeof RevokeHubTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

