// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file control/v1/control.proto (package control.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AckMotorCommandEventRequest, AckMotorCommandEventResponse, CreateMotorCommandRequest, CreateMotorCommandResponse, GetMotorCommandStatusRequest, GetMotorCommandStatusResponse, PullPendingMotorCommandsRequest, PullPendingMotorCommandsResponse } from "./control_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ====== Service ======
 *
 * @generated from service control.v1.ControlService
 */
export const ControlService = {
  typeName: "control.v1.ControlService",
  methods: {
    /**
     * User-created RPC: enqueue a motor command for a node behind a hub.
     *
     * @generated from rpc control.v1.ControlService.CreateMotorCommand
     */
    createMotorCommand: {
      name: "CreateMotorCommand",
      I: CreateMotorCommandRequest,
      O: CreateMotorCommandResponse,
      kind: MethodKind.Unary,
    },
    /**
     * User-created RPC: retrieve the current status of a previously-created command.
     *
     * @generated from rpc control.v1.ControlService.GetMotorCommandStatus
     */
    getMotorCommandStatus: {
      name: "GetMotorCommandStatus",
      I: GetMotorCommandStatusRequest,
      O: GetMotorCommandStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Hub-polled RPC: pull pending commands and lease them to the polling hub for bounded execution.
     *
     * @generated from rpc control.v1.ControlService.PullPendingMotorCommands
     */
    pullPendingMotorCommands: {
      name: "PullPendingMotorCommands",
      I: PullPendingMotorCommandsRequest,
      O: PullPendingMotorCommandsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Hub-ack RPC: acknowledge delivery/execution progress and terminal outcomes for a command.
     *
     * @generated from rpc control.v1.ControlService.AckMotorCommandEvent
     */
    ackMotorCommandEvent: {
      name: "AckMotorCommandEvent",
      I: AckMotorCommandEventRequest,
      O: AckMotorCommandEventResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

