// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file garden/v1/garden.proto (package garden.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// test comment

import { GetSummaryRequest, GetSummaryResponse, InsertSensorDataRequest, InsertSensorDataResponse } from "./garden_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ====== Service ======
 *
 * @generated from service garden.v1.GardenService
 */
export const GardenService = {
  typeName: "garden.v1.GardenService",
  methods: {
    /**
     * * 
     * Insère une nouvelle mesure capteur
     *
     * **Authentication:** Requires service account token (Hub only)
     * **Authorization:** Only service accounts without email can write
     *
     * @generated from rpc garden.v1.GardenService.InsertSensorData
     */
    insertSensorData: {
      name: "InsertSensorData",
      I: InsertSensorDataRequest,
      O: InsertSensorDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * * 
     * Récupère un résumé agrégé sur une fenêtre de temps
     *
     * **Authentication:** Requires valid user or service account token
     *
     * @generated from rpc garden.v1.GardenService.GetSummary
     */
    getSummary: {
      name: "GetSummary",
      I: GetSummaryRequest,
      O: GetSummaryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

